spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_user?useSSL=true&requireSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
      naming:
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8084
