spring:
  datasource:
    url: jdbc:mariadb://mysql/db_product?useSSL=false&trustServerCertificate=true&serverTimezone=UTC
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: password
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    showSql: false
    hibernate:
      ddlAuto: update