spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mariadb://localhost:3306/db_product?useSSL=false&trustServerCertificate=true&serverTimezone=UTC
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    showSql: false
    hibernate:
      ddlAuto: update
      naming:
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 20201117234756
server:
  port: 8999
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health, heapdump, prometheus
