spring:
  application:
    name: unit-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_product?useSSL=true&requireSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
      naming:
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  cloud:
#    kubernetes:
#      reload:
#        enabled: true
#      config:
#        name: unit-configmap
#        namespace: default
server:
  port: 8083
springdoc:
  api-docs:
    path: /api-docs
